const BAD_REQUEST = 400;
const AUTH_ERROR = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const CONFLICT = 409;
const DEFAULT = 500;

module.exports = {
  BAD_REQUEST,
  AUTH_ERROR,
  FORBIDDEN,
  NOT_FOUND,
  DEFAULT,
  CONFLICT,
};
